import datetime
from typing import Dict


class ReportGenerator:
    def __init__(self):
        pass

    def generate_dead_live_report(self, input_params: Dict, results: Dict) -> str:
        building_name = input_params.get("building_name", "未命名建筑")
        area = input_params.get("area", 0)
        floor_height = input_params.get("floor_height", 0)
        wall_thickness = input_params.get("wall_thickness", 0)
        building_type = input_params.get("building_type", "办公楼")

        report = []
        report.append("=" * 70)
        report.append("")
        report.append("             建 筑 荷 载 计 算 书")
        report.append("")
        report.append("=" * 70)
        report.append("")
        report.append(f"工程名称：{building_name}")
        report.append(f"计算类型：恒荷载与活荷载计算")
        report.append(f"计算日期：{datetime.datetime.now().strftime('%Y年%m月%d日')}")
        report.append(f"规范依据：《建筑结构荷载规范》GB50009-2012")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("一、输入参数")
        report.append("")
        report.append(f"  1. 建筑类型：{building_type}")
        report.append(f"  2. 楼层面积：A = {area:.2f} m²")
        report.append(f"  3. 楼层层高：H = {floor_height:.2f} m")
        report.append(f"  4. 墙体厚度：t = {wall_thickness:.3f} m")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("二、恒荷载计算")
        report.append("")
        report.append("【1】楼板自重")
        report.append("    板厚 h = 0.12 m")
        report.append("    混凝土容重 γ_c = 25.0 kN/m³")
        report.append(f"    g1 = h × γ_c = 0.12 × 25.0 = {results.get('楼板自重', {}).get('value', 0):.3f} kN/m²")
        report.append("")
        report.append("【2】楼面装修")
        report.append(f"    g2 = 0.400 kN/m² (水泥砂浆面层)")
        report.append("")
        report.append("【3】吊顶重量")
        report.append(f"    g3 = 0.300 kN/m² (轻钢龙骨吊顶)")
        report.append("")
        report.append("【4】墙体重量（均布）")
        report.append(f"    墙体线密度 = {wall_thickness:.3f} × 20.0 + 2 × 0.02 × 20.0 = {wall_thickness*20 + 0.8:.3f} kN/m²")
        report.append(f"    建筑周长 L = 4 × √A = 4 × √{area:.2f} = {4 * (area ** 0.5):.2f} m")
        report.append(f"    墙体总面积 = L × H = {4 * (area ** 0.5):.2f} × {floor_height:.2f} = {(4 * (area ** 0.5)) * floor_height:.2f} m²")
        report.append(f"    开窗率 20%，墙体净面积 = {(4 * (area ** 0.5)) * floor_height * 0.8:.2f} m²")
        report.append(f"    墙体均布重量 g4 = {results.get('墙体重量', {}).get('value', 0):.3f} kN/m²")
        report.append("")
        report.append("【5】门窗重量（均布）")
        report.append(f"    门窗线荷载 g5 = {results.get('门窗重量', {}).get('value', 0):.3f} kN/m²")
        report.append("")
        report.append("【6】总恒荷载标准值")
        gk_total = results.get('恒载标准值(面荷载)', {}).get('value', 0)
        report.append(f"    g_k = g1 + g2 + g3 + g4 + g5")
        report.append(f"        = {results.get('楼板自重', {}).get('value', 0):.3f} + {results.get('楼面装修', {}).get('value', 0):.3f} + {results.get('吊顶重量', {}).get('value', 0):.3f} + {results.get('墙体重量', {}).get('value', 0):.3f} + {results.get('门窗重量', {}).get('value', 0):.3f}")
        report.append(f"        = {gk_total:.3f} kN/m²")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("三、活荷载计算")
        report.append("")
        qk = results.get('活载标准值(面荷载)', {}).get('value', 0)
        report.append(f"  使用功能：{building_type}")
        report.append(f"  依据 GB50009-2012 表5.1.1")
        report.append(f"  活荷载标准值 q_k = {qk:.2f} kN/m²")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("四、荷载组合与汇总")
        report.append("")
        g_total = results.get('恒载标准值(总荷载)', {}).get('value', 0)
        q_total = results.get('活载标准值(总荷载)', {}).get('value', 0)
        report.append(f"  【1】总恒荷载标准值：G_k = {gk_total:.3f} × {area:.2f} = {g_total:.2f} kN")
        report.append(f"  【2】总活荷载标准值：Q_k = {qk:.2f} × {area:.2f} = {q_total:.2f} kN")
        report.append("")
        report.append("  【3】基本组合（承载力极限状态）：")
        combo_per_m2 = results.get('荷载组合(1.2恒+1.4活)', {}).get('value', 0)
        combo_total = results.get('总荷载设计值', {}).get('value', 0)
        report.append(f"      S = 1.2 × G_k + 1.4 × Q_k")
        report.append(f"        = 1.2 × {gk_total:.3f} + 1.4 × {qk:.2f} = {combo_per_m2:.3f} kN/m²")
        report.append(f"        = 1.2 × {g_total:.2f} + 1.4 × {q_total:.2f} = {combo_total:.2f} kN")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("五、计算结果汇总表")
        report.append("")
        report.append("  ┌──────────────────────┬──────────────┬──────────┐")
        report.append("  │      荷载项目        │     数值     │   单位   │")
        report.append("  ├──────────────────────┼──────────────┼──────────┤")
        report.append(f"  │ 恒载标准值(面荷载)   │  {gk_total:>10.3f}  │  kN/m²  │")
        report.append(f"  │ 活载标准值(面荷载)   │  {qk:>10.3f}  │  kN/m²  │")
        report.append(f"  │ 恒载标准值(总荷载)   │  {g_total:>10.2f}  │  kN     │")
        report.append(f"  │ 活载标准值(总荷载)   │  {q_total:>10.2f}  │  kN     │")
        report.append(f"  │ 荷载组合(面荷载)     │  {combo_per_m2:>10.3f}  │  kN/m²  │")
        report.append(f"  │ 总荷载设计值         │  {combo_total:>10.2f}  │  kN     │")
        report.append("  └──────────────────────┴──────────────┴──────────┘")
        report.append("")
        report.append("=" * 70)
        report.append("")
        report.append(f"计算人：建算通系统  v1.0")
        report.append(f"校对人：自动生成")
        report.append("")
        report.append("=" * 70)

        return "\n".join(report)

    def generate_wind_report(self, input_params: Dict, results: Dict) -> str:
        building_name = input_params.get("building_name", "未命名建筑")
        region = input_params.get("region", "北京")
        height = input_params.get("height", 0)
        shape_factor = input_params.get("shape_factor", 1.3)

        w0 = results.get('基本风压 w0', {}).get('value', 0)
        mu_z = results.get('高度变化系数 μz', {}).get('value', 0)
        beta_z = results.get('风振系数 βz', {}).get('value', 0)
        mu_s = results.get('体型系数 μs', {}).get('value', 0)
        wk = results.get('风荷载标准值 wk', {}).get('value', 0)

        report = []
        report.append("=" * 70)
        report.append("")
        report.append("             风 荷 载 计 算 书")
        report.append("")
        report.append("=" * 70)
        report.append("")
        report.append(f"工程名称：{building_name}")
        report.append(f"计算类型：风荷载计算")
        report.append(f"计算日期：{datetime.datetime.now().strftime('%Y年%m月%d日')}")
        report.append(f"规范依据：《建筑结构荷载规范》GB50009-2012")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("一、输入参数")
        report.append("")
        report.append(f"  1. 所在地区：{region}")
        report.append(f"  2. 建筑高度：H = {height:.2f} m")
        report.append(f"  3. 体型系数：μs = {mu_s:.2f}")
        report.append("  4. 地貌类型：B类（郊区、丘陵、中小城镇）")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("二、风荷载计算")
        report.append("")
        report.append("  计算公式：")
        report.append("  w_k = β_z × μ_s × μ_z × w_0")
        report.append("")
        report.append("  【1】基本风压 w_0")
        report.append(f"      根据 GB50009-2012，{region} 地区基本风压：")
        report.append(f"      w_0 = {w0:.2f} kN/m²")
        report.append("")
        report.append("  【2】体型系数 μ_s")
        report.append(f"      μ_s = {mu_s:.2f} （矩形封闭式建筑取 1.3）")
        report.append("")
        report.append("  【3】风压高度变化系数 μ_z")
        report.append(f"      建筑高度 H = {height:.2f} m，B类地貌")
        report.append(f"      查表 GB50009-2012 表8.2.1：")
        report.append(f"      μ_z = {mu_z:.4f}")
        report.append("")
        report.append("  【4】风振系数 β_z")
        if height <= 30:
            report.append(f"      高度 H ≤ 30m，取 β_z = {beta_z:.1f}")
        else:
            report.append(f"      高度 H > 30m，考虑风振：β_z = {beta_z:.4f}")
        report.append("")
        report.append("  【5】风荷载标准值 w_k")
        report.append(f"      w_k = β_z × μ_s × μ_z × w_0")
        report.append(f"          = {beta_z:.4f} × {mu_s:.2f} × {mu_z:.4f} × {w0:.2f}")
        report.append(f"          = {wk:.4f} kN/m²")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("三、计算结果汇总表")
        report.append("")
        report.append("  ┌──────────────────────┬──────────────┬──────────┐")
        report.append("  │      计算项目        │     数值     │   单位   │")
        report.append("  ├──────────────────────┼──────────────┼──────────┤")
        report.append(f"  │ 基本风压 w₀          │  {w0:>10.2f}  │  kN/m²  │")
        report.append(f"  │ 体型系数 μ_s         │  {mu_s:>10.2f}  │  -      │")
        report.append(f"  │ 高度变化系数 μ_z     │  {mu_z:>10.4f}  │  -      │")
        report.append(f"  │ 风振系数 β_z         │  {beta_z:>10.4f}  │  -      │")
        report.append(f"  │ 风荷载标准值 w_k     │  {wk:>10.4f}  │  kN/m²  │")
        report.append("  └──────────────────────┴──────────────┴──────────┘")
        report.append("")
        report.append("=" * 70)
        report.append("")
        report.append(f"计算人：建算通系统  v1.0")
        report.append(f"校对人：自动生成")
        report.append("")
        report.append("=" * 70)

        return "\n".join(report)

    def generate_snow_report(self, input_params: Dict, results: Dict) -> str:
        building_name = input_params.get("building_name", "未命名建筑")
        region = input_params.get("region", "北京")
        roof_type = input_params.get("roof_type", "平屋面(i≤5°)")

        s0 = results.get('基本雪压 s0', {}).get('value', 0)
        mu_r = results.get('积雪分布系数 μr', {}).get('value', 0)
        sk = results.get('雪荷载标准值 sk', {}).get('value', 0)
        snow_district = results.get('雪压分区', {}).get('value', '-')

        report = []
        report.append("=" * 70)
        report.append("")
        report.append("             雪 荷 载 计 算 书")
        report.append("")
        report.append("=" * 70)
        report.append("")
        report.append(f"工程名称：{building_name}")
        report.append(f"计算类型：雪荷载计算")
        report.append(f"计算日期：{datetime.datetime.now().strftime('%Y年%m月%d日')}")
        report.append(f"规范依据：《建筑结构荷载规范》GB50009-2012")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("一、输入参数")
        report.append("")
        report.append(f"  1. 所在地区：{region}")
        report.append(f"  2. 屋面类型：{roof_type}")
        report.append(f"  3. 雪压分区：{snow_district} 区")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("二、雪荷载计算")
        report.append("")
        report.append("  计算公式：")
        report.append("  s_k = μ_r × s_0")
        report.append("")
        report.append("  【1】基本雪压 s_0")
        report.append(f"      根据 GB50009-2012 附录E，{region} 地区基本雪压：")
        report.append(f"      s_0 = {s0:.2f} kN/m²")
        report.append("")
        report.append("  【2】屋面积雪分布系数 μ_r")
        report.append(f"      屋面类型：{roof_type}")
        report.append(f"      查表 GB50009-2012 表6.2.1：")
        report.append(f"      μ_r = {mu_r:.2f}")
        report.append("")
        report.append("  【3】雪荷载标准值 s_k")
        report.append(f"      s_k = μ_r × s_0")
        report.append(f"          = {mu_r:.2f} × {s0:.2f}")
        report.append(f"          = {sk:.4f} kN/m²")
        report.append("")
        report.append("-" * 70)
        report.append("")
        report.append("三、计算结果汇总表")
        report.append("")
        report.append("  ┌──────────────────────┬──────────────┬──────────┐")
        report.append("  │      计算项目        │     数值     │   单位   │")
        report.append("  ├──────────────────────┼──────────────┼──────────┤")
        report.append(f"  │ 基本雪压 s₀          │  {s0:>10.2f}  │  kN/m²  │")
        report.append(f"  │ 积雪分布系数 μ_r     │  {mu_r:>10.2f}  │  -      │")
        report.append(f"  │ 雪荷载标准值 s_k     │  {sk:>10.4f}  │  kN/m²  │")
        report.append("  └──────────────────────┴──────────────┴──────────┘")
        report.append("")
        if s0 == 0:
            report.append("  注：该地区基本雪压为 0，无需考虑雪荷载作用。")
            report.append("")
        report.append("=" * 70)
        report.append("")
        report.append(f"计算人：建算通系统  v1.0")
        report.append(f"校对人：自动生成")
        report.append("")
        report.append("=" * 70)

        return "\n".join(report)

    def report_to_text(self, report_content: str, filepath: str):
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report_content)
        return filepath
